import { Link, useParams } from "react-router-dom";
import { ArrowLeft, BriefcaseBusiness, CheckCircle2, Code2, GraduationCap } from "lucide-react";
import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
import { SCHOOL_IMAGES } from "@/lib/schoolImages";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
export default function JurusanDetail(){const {id}=useParams();const [j,setJ]=useState(null);useEffect(()=>{if(supabase&&!id.startsWith("demo-"))supabase.from("jurusan").select("*").eq("id",id).maybeSingle().then(({data})=>setJ(data))},[id]);if(!j)return <div className="container-app py-16"><Link to="/jurusan" className="inline-flex items-center gap-2 text-sm font-bold text-slate-500"><ArrowLeft size={16}/> Kembali ke jurusan</Link><div className="mt-8 rounded-[32px] bg-gradient-to-br from-emerald-50 to-cyan-50 p-10"><Badge>PROGRAM KEAHLIAN</Badge><h1 className="mt-4 text-4xl font-black">Informasi Jurusan</h1><p className="mt-3 text-slate-500">Pilih jurusan dari halaman daftar untuk melihat detail yang tersedia.</p><Link to="/daftar"><Button className="mt-6">Daftar Sekarang</Button></Link></div></div>;return <div className="container-app py-14"><Link to="/jurusan" className="inline-flex items-center gap-2 text-sm font-bold text-slate-500"><ArrowLeft size={16}/> Semua jurusan</Link><div className="mt-7 grid overflow-hidden rounded-[32px] bg-gradient-to-br from-slate-950 to-emerald-950 text-white sm:grid-cols-[1fr_.7fr]"><div className="p-8 sm:p-12"><Badge className="border-white/10 bg-white/10 text-white">PROGRAM KEAHLIAN</Badge><h1 className="mt-5 max-w-3xl text-4xl font-black sm:text-5xl">{j.nama}</h1><p className="mt-5 max-w-3xl leading-7 text-slate-300">{j.deskripsi}</p></div><img src={SCHOOL_IMAGES.jurusan?.[j.nama] || SCHOOL_IMAGES.activity} alt={`Kegiatan ${j.nama}`} className="h-full min-h-64 w-full object-cover"/></div><div className="mt-7 grid gap-5 lg:grid-cols-2"><Info icon={Code2} title="Kompetensi yang dipelajari" text={j.kompetensi}/><Info icon={BriefcaseBusiness} title="Prospek lulusan" text={j.prospek}/></div><Link to="/daftar"><Button size="lg" className="mt-7 rounded-2xl">Pilih jurusan ini <GraduationCap size={18}/></Button></Link></div>}
function Info({icon:Icon,title,text}){return <div className="rounded-[26px] border border-slate-200 bg-white p-7"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-emerald-50 text-emerald-600"><Icon/></div><h2 className="mt-5 text-xl font-black">{title}</h2><p className="mt-3 leading-7 text-slate-500">{text||"Informasi akan diperbarui oleh admin sekolah."}</p><div className="mt-5 flex items-center gap-2 text-sm font-bold text-emerald-600"><CheckCircle2 size={16}/> Informasi program keahlian</div></div>}
